---
- name:      Install tools to ensure logging will work.
  apt:       pkg={{item}} state=present update_cache=yes
  sudo:      yes
  with_items:
    - rsyslog
    - rsyslog-gnutls
- name: Change the kernel.hostname
  sysctl: name=kernel.hostname value="webserver-{{hostname}}" present=yes

- include:   papertrailapp.yml
#- include: loggly.yml
- name:      Restart rsyslog
  service:   name=rsyslog state=restarted
  sudo:      yes
  register:  restart_rsyslog
- debug:     var=restart_rsyslog
