---
- name:      "Install the cert into the certs directory"
  copy:      src={{ logging.papertrailapp.cert.name }} dest={{ logging.papertrailapp.cert.path}} owner=root group=root mode=0644
  sudo:      yes

- name:      "Copy the template to the rsyslog.d dir"
  template:  src=papertrailapp.rsyslog.conf.j2 dest={{ logging.rsyslog.dir }}/999-papertraillapp.rsyslog.conf owner=root group=root mode=0644
  sudo:      yes
